env:
  MONGO_TOKEN: 

on:
  pull_request:
    branches:
      - '**'
jobs:
  test:
    name: integration tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: | 
        npm install
        npx playwright install
    
    - name: get mongo token
      run: |
        npm install -g vercel@latest
        vercel link -y --token=${{secrets.VERCEL_TOKEN}} -p portfolio
        vercel env pull --token=${{secrets.VERCEL_TOKEN}} "./vercel_envs"
        echo "MONGO_TOKEN=$(cat './vercel_envs' | grep mongo_db_uri | cut -d '"' -f2)" >> $GITHUB_ENV
        echo ${{env.MONGO_TOKEN}}

    - name: test
      run: |
        echo $MONGO_TOKEN
        npm run test --mongo_db_uri=${{env.MONGO_TOKEN}}
